### ISSUE TITLE
Add the Search and Filter bar on top of the cards

### ISSUE THREAD

**Issue by pr0ximaCent** [pr0ximaCent/Grey-Matter#11]
Masbah will implement the backend, just implement the UI on top. 

**also for heading use this:
horizontal line effect:**

"image for visualisation":
![image](https://github.com/user-attachments/assets/8a6a4da3-1a00-4394-b45f-3b47a8e7a47a)

const HorizontalLine = () => {
  const lineStyle = {
    width: '100%',
    height: '1px',
    backgroundColor: 'white',
    margin: '0',
    padding: '0',
    border: 'none'
  };

  return (
    <div className="text-n-2">
      <div style={lineStyle}></div>
    </div>
  );
};

export default HorizontalLine;

<HorizontalLine/><br></br>
      <h1 className="h1 mb-6 text-n-1" style={{ textAlign: 'center' }}>
       **Bangladedsh Scientists Rankings 2024**
      </h1>

**Comment by RJ-Hossan** [comment]
https://github.com/user-attachments/assets/448c9d9c-9950-448d-b785-fe576a97932e

Problem has been solved.
