### ISSUE TITLE
SignUp and SignIn Modal

### ISSUE THREAD

**Issue by RJ-Hossan** [pr0ximaCent/Grey-Matter#5]
@ma5bah In running website, **SignUp and SignIn Modal** looks ok. But there arises some conflict in this git repo which is showing following design which is not **OK**. It should be same as running **SignUp and SignIn Modal** as following 2nd picture.
![temp3](https://github.com/user-attachments/assets/0dd00e32-bbe9-4d31-b86a-69f60188c092)
![temp4](https://github.com/user-attachments/assets/94a7d707-1fee-4564-a40c-dc4bd54d9bb3)

**Comment by 5pace4** [comment]
SignUp and SignIn Modal #5 issue solved
